openapi: 3.0.0
info:
  title: project
  description: project API
  version: '1.0'
  contact:
    email: tim.miller@sage.com
    name: Tim Miller
# servers:
#   - url: 'http://localhost:3000'
tags:
  - name: project
paths:
  '/objects/project/{key}':
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
        description: project Key
    get:
      summary: Get project
      description: Get complete details for a particular project
      tags:
        - project
      responses:
        '200':
          description: OK
          content:
            application/json:
      operationId: get-objects-project-key
    delete:
      summary: Delete project
      description: Delete a project
      tags:
        - project
      operationId: delete-v1-objects-project-key
      responses:
        '204':
          description: No Content
    patch:
      summary: Update project
      operationId: put-objects-project-key
      description: Update details of existing project
      tags:
        - project
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: ../models/project.s1.schema.yaml
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              example-1:
                value:
                  key: string
                  id: string
                  name: string
                  description: string
                  currency: string
                  category: string
                  projectStatus:
                    key: '0'
                    id: string
                    name: string
                  status: active
                  startDate: string
                  endDate: string
                  amounts:
                    budgetAmount: 0
                    contractAmount: 0
                    actualAmount: 0
                  durations:
                    budgetDuration: 0
                    estimatedDuration: 0
                    actualDuration: 0
                    approvedDuration: 0
                    remainingDuration: 0
                  percentComplete: 0
                  observedPercentComplete: 0
                  billingType: string
                  salesOrderId: string
                  purchaseOrderId: string
                  purchaseOrderAmount: string
                  purchaseQuoteId: string
                  salesforceKey: string
                  parent:
                    key: string
                    id: string
                    name: string
                  isInvoicedWithParent: true
                  customer:
                    key: 0
                    id: string
                    name: string
                  salesContact:
                    key: string
                    id: string
                    name: string
                    href: string
                  manager:
                    key: string
                    id: string
                    name: string
                    href: string
                  department:
                    key: 0
                    id: string
                    name: string
                  location:
                    key: 0
                    id: 0
                    name: string
                  referenceId: string
                  budgetedCost: 0
                  class:
                    id: string
                    key: 0
                    name: string
                  userRestrictions: string
                  isEmployeeExpenseBillable: true
                  isAccountsPayableOrPurchaseOrderBillable: string
                  billingRate: 0
                  billingPricing: string
                  expenseRate: string
                  expensePricing: string
                  rateForAPOrPurchasing: 0
                  pricingOptionForAccountsPayableOrPurchaseOrder: string
                  contacts:
                    primary:
                      key: string
                      id: string
                      href: string
                    shipTo:
                      key: string
                      id: string
                      href: string
                    billTo:
                      key: string
                      id: string
                      href: string
                  invoiceMessage: string
                  invoiceCurrency: string
                  billingAmountOverMax: string
                  isExpenseExcluded: true
                  attachmentId: string
                  audit:
                    createdDateTime: '2014-01-08T11:28:12Z'
                    modifiedDateTime: '2014-01-08T11:28:12Z'
                    createdBy: 1
                    modifiedBy: 95
                  root:
                    key: 0
                    id: string
                    name: string
              working example:
                value:
                  salesContact:
                    id: '12'
                  manager:
                    id: '13'
                  contacts:
                    primary:
                      id: jrenzel
                    shipTo:
                      id: jrenzel
                    billTo:
                      id: anjali.israni
components:
  schemas:
    project:
      $ref: ../models/project.s1.schema.yaml
    projectRequiredProperties:
      type: object
      required:
        - id
        - name
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
  parameters:
    jobId:
      name: jobId
      in: path
      schema:
        type: string
        pattern: '^[A-Za-z0-9]'
      required: true

